---
- name: install required system packages
  become: true
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - npm
    - nodejs-legacy
    - tor
    - privoxy
    - supervisor

# Install vendor NodeJS when the system's is too old.
- include: tasks/vendor-nodejs.yml

- name: create bridge user
  become: true
  user: name={{ bridgeuser }}

- name: create Git repo directory
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ git_clone_path | dirname }} state=directory

- name: clone Git repo
  become: true
  become_user: "{{ bridgeuser }}"
  git: repo={{ git_repo_url }} dest={{ git_clone_path }} accept_hostkey=yes

- name: link bridge source to final destination
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ bridge_path }} state=link src={{ git_clone_path }}/ceno-box/ceno-bridge

- name: create protected bridge configuration directory
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ bridge_path }}/.CENO state=directory mode=0700

- name: install Bundle Server NodeJS packages
  become: true
  become_user: "{{ bridgeuser }}"
  npm: path={{ bridge_path }}/bundle-server

- name: configure Privoxy to use Tor
  become: true
  lineinfile: >
    dest=/etc/privoxy/config
    regexp='^#+(\s*forward-socks5\s+/\s+127\.0\.0\.1:9050\s+\.\s*.*)'
    line='\1' backrefs=yes
  notify: restart Privoxy

- name: run CENO services under Supervisor
  become: true
  template: src=supervisor-ceno.conf.j2 dest=/etc/supervisor/conf.d/ceno.conf
  notify: restart Supervisor
