---
- name: install required system packages
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - npm
    - nodejs-legacy

- name: create bridge user
  become: true
  user: name={{ bridgeuser }}

- name: create Git repo directory
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ git_clone_path | dirname }} state=directory

- name: clone Git repo
  become: true
  become_user: "{{ bridgeuser }}"
  git: repo={{ git_repo_url }} dest={{ git_clone_path }} accept_hostkey=yes

- name: link bridge source to final destination
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ bridge_path }} state=link src={{ git_clone_path }}/ceno-bridge

- name: create protected bridge configuration directory
  become: true
  become_user: "{{ bridgeuser }}"
  file: name={{ bridge_path }}/.CENO state=directory mode=0700

- name: install NodeJS packages
  become: true
  become_user: "{{ bridgeuser }}"
  npm: path={{ bridge_path }}
